/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testforc_com_zou_testforc_VirtualTouchJni */

#ifndef _Included_testforc_com_zou_testforc_VirtualTouchJni
#define _Included_testforc_com_zou_testforc_VirtualTouchJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testforc_com_zou_testforc_VirtualTouchJni
 * Method:    down
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_testforc_com_zou_testforc_VirtualTouchJni_down
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     testforc_com_zou_testforc_VirtualTouchJni
 * Method:    move
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_testforc_com_zou_testforc_VirtualTouchJni_move
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     testforc_com_zou_testforc_VirtualTouchJni
 * Method:    up
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_testforc_com_zou_testforc_VirtualTouchJni_up
  (JNIEnv *, jobject, jint);

/*
 * Class:     testforc_com_zou_testforc_VirtualTouchJni
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testforc_com_zou_testforc_VirtualTouchJni_commit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
